baseURL: https://ajimoh2023-portfolio.netlify.app/
languageCode: en-us
title: Portfolio website for Ameera Jimoh
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      CONTENT:
      COURSE MATERIAL, PROJECTS
    title: Hi, my name is Ameera and I am a MFA student at LBS and this website is for DSB2023
  blog: {}
  contact:
    address:
      - city: London
        country: England
        street: The Regent's Park
        title: London Business School
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: ajimoh.mfa2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (647) 627-7220 x1
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: London Business School
    enable: yes
    quicklinks:
     - alt: HTML5 UP
       text: 'Design: '
       url: https://www.html5up.net
    social:
      # - icon: fa-twitter
      #   label: Twitter
      #   url: https://www.twitter.com
      # - icon: fa-facebook
      #   label: Facebook
      #   url: https://www.facebook.com
      # - icon: fa-instagram
      #   label: Instagram
      #   url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/ameerajimoh
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/ameerajimoh/ 
  image: ''
  name: 
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      #- name: Generic Blog
       # url: blogs/ipsum
      #- name: Elements
       # url: elements.html
    menu: Menu
   # subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: stockjpg.jpeg
        subtitle: Risk-Return of DJIA stocks
        title: Stock Analysis
        url: blogs/risk_return
      - image: datajpg.jpeg
        subtitle: Unlocking Opportunities with Data
        title: The Data Analytics Advantage
        url: blogs/dataanalytics
      - image: lang.jpeg
        subtitle: A1 Spanish
        title: Languages
        url: blogs/languages
      - image: sports.webp
        subtitle: Active Hobbies
        title: Sports and Activities
        url: blogs/sports
      - image: flights.webp
        subtitle: Data Manipulation and Analysis of Flights
        title: Analyzing Flight Details
        url: blogs/flights
      - image: scrap01.png
        subtitle: Scaping for Positions- Consulting Jobs
        title: Web Scaping
        url: blogs/scraping
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Welcome to my website for DSB2023 course!
      \n    Here, you'll find a collection of my previous projects completed using R, showcasing the power of data analytics. \n   
     Additionally, I share captivating blogs that delve into my personal interests, hobbies, and reflections on my time at London Business School. \n  
     Join me on this journey of exploration and discovery as we unlock the potential of data and share memorable experiences along the way."
    title: Welcome Message
    url: blogs
markup: 
  goldmark: 
    renderer: 
      unsafe: true