[build] 
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.111.3"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"
  
[context.branch-deploy.environment]
  HUGO_VERSION = "0.111.3"

[context.deploy-preview.environment]
<<<<<<< HEAD
  HUGO_VERSION = "0.113.0"  
=======
  HUGO_VERSION = "0.111.3"  
>>>>>>> 32cca3f531f443cb8306eb4869de7142d7bf9d8b
